### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by fractional-ray** [VectorPosse/Bayes#1]
There is a small typo on line 110, the typo is distibution. If you wanted I could fork and make a PR.

Best,
Isaiah

**Comment by VectorPosse** [comment]
Nah, I'll fix it. (I just checked and there are actually several typos. Forgot to spell check that one.) Thanks, though.

**Comment by VectorPosse** [comment]
Since I last pushed to this repo, I've expanded the materials and split them into separate modules, so the last push just updated all that stuff.
